title: "ğŸŒ¸ æ–°å’OLã®FXå¥®é—˜è¨˜"
description: "æŠ•è³‡åˆå¿ƒè€…ã®ç§ãŒFXã«æŒ‘æˆ¦ï¼å£åº§é–‹è¨­ã‹ã‚‰å­¦ã‚“ã ã“ã¨ã¾ã§ã‚·ã‚§ã‚¢ã—ã¾ã™ã€‚"
baseurl: ""
url: "https://lifestyle-cmyk.github.io"
theme: minima
markdown: kramdown
